"use strict";
exports.__esModule = true;
var parse_1 = require("./parse");
exports.parse = parse_1.parse;
var semantics_1 = require("./semantics");
exports.types = semantics_1.types;
var semantics_2 = require("./semantics");
exports.scope = semantics_2.scope;
var paths_1 = require("./paths");
exports.paths = paths_1.paths;
var error_1 = require("./error");
exports.error = error_1.error;
